### ISSUE TITLE
MANUALLY INSTALL didn't generate .natrium

### ISSUE THREAD

**Issue by dangthaison91** [e-sites/Natrium#12]
Try to use manually install by dragging latest `natrium` bin file into project folder but it didn't generate `.natrium` folder or anything.

I tried the Cocoapods way and it works. But there is an error that is reported in #11 

PS: Really nice ideas and helpful library.

**Comment by basvankuijck** [comment]
Have you read the [manual installation guide](https://github.com/e-sites/Natrium/blob/master/docs/INSTALL_MANUALLY.md)?

In particular the scheme setup?
Else take a look at the [Example proejct](https://github.com/e-sites/Natrium/tree/master/Example/Manual)

**Comment by dangthaison91** [comment]
@basvankuijck Yes, I followed your guide but it didn't work, nothing is generated.

**Comment by basvankuijck** [comment]
@dangthaison91: Could you open the terminal in the project root and type:

```bash
chmod +x ./natrium
```

And then try again?

**Comment by dangthaison91** [comment]
Yeah, it works now. Thanks for quickly support @basvankuijck

**Comment by basvankuijck** [comment]
@dangthaison91: No problem, glad to help. I updated the guide, so people don't miss this step. Has probably something to do with the way github 'packs' those binaries without extensions
