### ISSUE TITLE
Launch_screen_versioning is not optional

### ISSUE THREAD

**Issue by dangthaison91** [e-sites/Natrium#16]
On version 6.1.2, **launch_screen_versioning** is not optional anymore. If it is not set, Natrium will produce error:

**Version 6.1.2:**

```ruby
12/10/18, 1:01:06 AM -   [launch_screen_versioning]
12/10/18, 1:01:06 AM -     -empty-
12/10/18, 1:01:06 AM - ❌  Missing 'path' parameter for 'launch_screen_versioning' key
```

**Comment by basvankuijck** [comment]
Could you retry it from the current (updated) 6.1.2 version?

**Comment by dangthaison91** [comment]
@basvankuijck Yes, this issue only occurs with version 6.1.2 as I mentioned above.

**Comment by basvankuijck** [comment]
Have you tried the lastest (`master`) release?

**Comment by dangthaison91** [comment]
Wow, It worked, great work @basvankuijck. Thanks!!!!
