### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by idoNaveh** [e-sites/Natrium#2]
Is it possible to add support for Carthage?

**Comment by basvankuijck** [comment]
In theory it's possible, but would require some manual installation steps.
I'll have a look

**Comment by basvankuijck** [comment]
Carthage support has been added.
Follow the [README](https://github.com/e-sites/Natrium/blob/master/README.md) and specifically the [Carthage installation steps](https://github.com/e-sites/Natrium/blob/master/docs/INSTALL_CARTHAGE.md).

**Comment by idoNaveh** [comment]
Thanks!
