### ISSUE TITLE
Not able to set PRODUCT_BUNDLE_IDENTIFIER.

### ISSUE THREAD

**Issue by phaninderm** [e-sites/Natrium#25]
I've used CocoaPods to install the framework. I'm not able to set the PRODUCT_BUNDLE_IDENTIFIER for different environments.

I've made sure that I've added the Pre-Actions in Scheme information.

I'm able to change Variables but not the PRODUCT_BUNDLE_IDENTIFIER

**Comment by basvankuijck** [comment]
Could you run: `xcodebuild -showBuildSettings -workspace App.xcworkspace -scheme "App" -configuration Debug`

Does the `PRODUCT_BUNDLE_IDENTIFIER` have any value, and is it one of the values you defined in your `.natrium.yml`?

If not: Could you check that you haven't manually overriden the `PRODUCT_BUNDLE_IDENTIFIER` in your build settings for your target. You can see so if the value is bold.

You can also check the **Levels** tab in your target's build settings to see what level is responsible for your incorrect `PRODUCT_BUNDLE_IDENTIFIER`

The `Config.File` column should show your desired value.
