### ISSUE TITLE
Config Natrium With Installation CocoaPods

### ISSUE THREAD

**Issue by vantruong1094** [e-sites/Natrium#26]
why do not copy of file Natrium.swift, only make a reference to it?
I don't understand!

**Comment by basvankuijck** [comment]
Because during the pre-action run script natrium generates a `Natrium.swift` in the `Pods/Natrium/bin` folder.

If you add the file to your target AND copy it, a physical copy of the file will be placed in the (root) of your project and therefor it will not update once you run natrium.

**Comment by vantruong1094** [comment]
thanks your question!
