### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by pokryfka** [e-sites/Natrium#29]
Please support SPM installation.

https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

**Comment by basvankuijck** [comment]
v8.0.0 is now compatible with SwiftPM => https://github.com/e-sites/Natrium/blob/main/docs/INSTALL_SWIFTPM.md

**Comment by michala-pro** [comment]
@basvankuijck are you sure the path should be `"${BUILD_DIR%Build/*}/SourcePackages/checkouts/Natrium/Natrium/natrium"` does not work for me that way

**Comment by pokryfka** [comment]
@basvankuijck are you sure the path should be `"${BUILD_DIR%Build/*}/SourcePackages/checkouts/Natrium/Natrium/natrium"` ? 
does not work for me

**Comment by basvankuijck** [comment]
Hmms, I use the same path as firebase: https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md
And it seems to work for me, for a new / empty project.

If you 'right click' on "Natrium" under "Swift Package Dependencies" en then select "Show in Finder" 
What does it look like?

Something like this:
<img width="1221" alt="Screenshot 2021-01-21 at 08 12 35" src="https://user-images.githubusercontent.com/1327984/105315953-72a20000-5bc0-11eb-87bc-0bede72750ba.png">

(!) Folder names are case-sensitive, so you have to use `https://github.com/e-sites/Natrium.git` as the package git, and not `https://github.com/e-sites/natrium.git`

**Comment by pokryfka** [comment]
redone the steps and I works now 🤔 
thank you for that, one more Pod left ...
