### ISSUE TITLE
String variables should have `StaticString` type

### ISSUE THREAD

**Issue by pokryfka** [e-sites/Natrium#30]
For example:

```
        static let testVariableString: StaticString = "debugString"
```

instead of 

```
        static let testVariableString: String = "debugString"
```

**Comment by pokryfka** [comment]
Awesome, thank you!

**Comment by basvankuijck** [comment]
In addition, since v7.3.0 you should set this in your **.natrium.yml**:

```
settings:
   stringType: "StaticString"
```

stringType defaults to "String"

**Comment by pokryfka** [comment]
Makes sense, its a breaking change ...

Still I think its very useful to be able to identify string literals.
Thank you for the change and this comment, will update settings.
