### ISSUE TITLE
v5.8.0 is not working with Carthage

### ISSUE THREAD

**Issue by idoNaveh** [e-sites/Natrium#5]
Using Carthage with latest version 5.8.0 is not working.
The zip file is not a real zip file.

BTW - why Carthage build is using only zip instead supporting building from the project?

**Comment by basvankuijck** [comment]
Could you clean your cache:
`rm -rf ~/Library/Caches/org.carthage.CarthageKit`

and then try again?
`carthage update`

**Comment by idoNaveh** [comment]
Apparently the problem was old Carthage version. 
With Carthage v0.30.1 there is no problem to get the framework.
